### ISSUE TITLE
Nonexistent hostname crashes app

### ISSUE THREAD

**Issue by dentarg** [dentarg/urls#5]
```
SocketError at /
getaddrinfo: nodename nor servname provided, or not known
```

Problem is at `open(uri)` call

**Comment by dentarg** [comment]
Still true even after https://github.com/dentarg/urls/commit/8e40020db54d67126cbcb09f54c4dbf61a850de1

Repro: https://urls-app.herokuapp.com/?url=blog.trellooooooo.com

```
/app/vendor/ruby-2.4.5/lib/ruby/2.4.0/net/http.rb:906:in `rescue in block in connect': Failed to open TCP connection to blog.trellooooooo.com:80 (getaddrinfo: Name or service not known) (Faraday::ConnectionFailed)
/app/vendor/ruby-2.4.5/lib/ruby/2.4.0/net/http.rb:903:in `block in connect'
/app/vendor/ruby-2.4.5/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/app/vendor/ruby-2.4.5/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/app/vendor/ruby-2.4.5/lib/ruby/2.4.0/net/http.rb:902:in `connect'
/app/vendor/ruby-2.4.5/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
/app/vendor/ruby-2.4.5/lib/ruby/2.4.0/net/http.rb:876:in `start'
/app/vendor/ruby-2.4.5/lib/ruby/2.4.0/net/http.rb:1407:in `request'
/app/vendor/ruby-2.4.5/lib/ruby/2.4.0/net/http.rb:1165:in `get'
/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:78:in `perform_request'
/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:38:in `block in call'
/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:33:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/faraday-encoding-0.0.4/lib/faraday/encoding.rb:12:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection'
/app/vendor/bundle/ruby/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:66:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/gzip.rb:24:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/request/retry.rb:116:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/rack_builder.rb:143:in `build_response'
/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/connection.rb:387:in `run_request'
/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/connection.rb:138:in `get'
/app/vendor/bundle/ruby/2.4.0/gems/metainspector-5.4.1/lib/meta_inspector/request.rb:74:in `block in fetch'
/app/vendor/ruby-2.4.5/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/app/vendor/ruby-2.4.5/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
/app/vendor/ruby-2.4.5/lib/ruby/2.4.0/timeout.rb:33:in `catch'
/app/vendor/ruby-2.4.5/lib/ruby/2.4.0/timeout.rb:33:in `catch'
/app/vendor/ruby-2.4.5/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
/app/vendor/bundle/ruby/2.4.0/gems/metainspector-5.4.1/lib/meta_inspector/request.rb:51:in `fetch'
/app/vendor/bundle/ruby/2.4.0/gems/metainspector-5.4.1/lib/meta_inspector/request.rb:41:in `response'
/app/vendor/bundle/ruby/2.4.0/gems/metainspector-5.4.1/lib/meta_inspector/request.rb:25:in `initialize'
/app/vendor/bundle/ruby/2.4.0/gems/metainspector-5.4.1/lib/meta_inspector/document.rb:32:in `new'
/app/vendor/bundle/ruby/2.4.0/gems/metainspector-5.4.1/lib/meta_inspector/document.rb:32:in `initialize'
/app/vendor/bundle/ruby/2.4.0/gems/metainspector-5.4.1/lib/meta_inspector.rb:20:in `new'
/app/vendor/bundle/ruby/2.4.0/gems/metainspector-5.4.1/lib/meta_inspector.rb:20:in `new'
/app/lib/urls.rb:19:in `by_url'
/app/urls_app.rb:15:in `block in <top (required)>'
```
