### ISSUE TITLE
ArgumentError - invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by dentarg** [dentarg/urls#6]
```
2015-06-23T06:41:01.147627+00:00 heroku[router]: at=info method=GET path="/?url=http%3A%2F%2Fwww.bloggerspoint.dk%2F" host=urls-app.herokuapp.com request_id=77218322-6cce-4207-bb60-870e16a632f1 fwd="94.234.170.175" dyno=web.1 connect=1ms service=4267ms status=500 bytes=313
2015-06-23T06:41:01.144957+00:00 app[web.1]: ArgumentError - invalid byte sequence in UTF-8:
2015-06-23T06:41:01.144962+00:00 app[web.1]:    /app/vendor/ruby-2.2.2/lib/ruby/2.2.0/uri/rfc2396_parser.rb:267:in `scan'
2015-06-23T06:41:01.144964+00:00 app[web.1]:    /app/vendor/ruby-2.2.2/lib/ruby/2.2.0/uri/rfc2396_parser.rb:267:in `extract'
2015-06-23T06:41:01.144967+00:00 app[web.1]:    /app/lib/urls.rb:18:in `by_text'
2015-06-23T06:41:01.144966+00:00 app[web.1]:    /app/vendor/ruby-2.2.2/lib/ruby/2.2.0/uri/common.rb:293:in `extract'
2015-06-23T06:41:01.144969+00:00 app[web.1]:    /app/lib/urls.rb:14:in `by_url'
2015-06-23T06:41:01.144973+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
2015-06-23T06:41:01.144975+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
2015-06-23T06:41:01.144971+00:00 app[web.1]:    /app/urls_app.rb:14:in `block in <top (required)>'
2015-06-23T06:41:01.144977+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
2015-06-23T06:41:01.144979+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
2015-06-23T06:41:01.144981+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
2015-06-23T06:41:01.144982+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
2015-06-23T06:41:01.144984+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
2015-06-23T06:41:01.144986+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
2015-06-23T06:41:01.144987+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
2015-06-23T06:41:01.144989+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
2015-06-23T06:41:01.144991+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
2015-06-23T06:41:01.144992+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
2015-06-23T06:41:01.144994+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
2015-06-23T06:41:01.144996+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
2015-06-23T06:41:01.144997+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
2015-06-23T06:41:01.144999+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
2015-06-23T06:41:01.145000+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
2015-06-23T06:41:01.145001+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
2015-06-23T06:41:01.145003+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
2015-06-23T06:41:01.145004+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
2015-06-23T06:41:01.145006+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
2015-06-23T06:41:01.145007+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
2015-06-23T06:41:01.145009+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
2015-06-23T06:41:01.145010+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
2015-06-23T06:41:01.145012+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
2015-06-23T06:41:01.145013+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
2015-06-23T06:41:01.145015+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
2015-06-23T06:41:01.145016+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
2015-06-23T06:41:01.145017+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
2015-06-23T06:41:01.145019+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.2/lib/rack/logger.rb:15:in `call'
2015-06-23T06:41:01.145020+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.2/lib/rack/commonlogger.rb:33:in `call'
2015-06-23T06:41:01.145022+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:217:in `call'
2015-06-23T06:41:01.145023+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
2015-06-23T06:41:01.145025+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.2/lib/rack/head.rb:13:in `call'
2015-06-23T06:41:01.145026+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.2/lib/rack/methodoverride.rb:22:in `call'
2015-06-23T06:41:01.145028+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
2015-06-23T06:41:01.145029+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
2015-06-23T06:41:01.145030+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
2015-06-23T06:41:01.145032+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
2015-06-23T06:41:01.145041+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:576:in `process_client'
2015-06-23T06:41:01.145033+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
2015-06-23T06:41:01.145042+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:670:in `worker_loop'
2015-06-23T06:41:01.145045+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:140:in `start'
2015-06-23T06:41:01.145044+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
2015-06-23T06:41:01.145047+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/bin/unicorn:126:in `<top (required)>'
2015-06-23T06:41:01.145048+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `load'
2015-06-23T06:41:01.145050+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `<main>'
```

**Comment by dentarg** [comment]
This now works: https://urls-app.herokuapp.com/?url=http%3A%2F%2Fwww.bloggerspoint.dk%2F
